name: Deploy to Lightsail

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.LIGHTSAIL_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Lightsail
      run: |
        ssh ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
          # Load NVM
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install node
          nvm use node

          # Go to project directory
          cd /metafarmers-server

          # Git safe directory config
          git config --global --add safe.directory /metafarmers-server
          git pull origin main

          # Fix ownership for npm install (adjust user if needed)
          sudo chown -R ec2-user:ec2-user .

          # Install deps
          npm install --unsafe-perm

          # Start or restart app using pm2
          if pm2 list | grep -q app; then
            pm2 restart app
          else
            pm2 start server.js --name app
          fi
        EOF
